### ISSUE TITLE
using gsub! path, false gives an error

### ISSUE THREAD

**Issue by Skarlso** [Skarlso/jsonpathv2#3]
I cant replace a path with false. replacing with true works nicely.

```
doc.gsub! path, false
NoMethodError: undefined method `call' for nil:NilClass
from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsonpath-0.5.6/lib/jsonpath/enumerable.rb:95:in `yield_value'
```

Ping @kibs

**Comment by Skarlso** [comment]
Hi, I know this is old news... I'm maintaining this gem from now on. And would you be so kind as to try and provide some more information here, how you did this? What's the path, and if it's still an issue? 

Thanks!

**Comment by kibs** [comment]
Hi, long time ago, the problem was when you want to replace some path so it becomes false in the output it didn't work. I think it was some kind of "if" on the value, can't really remember. But i think it was easily reproduced, so just about any doc, like

```
doc = {"foobar": "baz"}.to_json
doc.gsub! "$.foobar", false
```

and then it fails. This is from the top of my head :)

**Comment by Skarlso** [comment]
Thanks for checking up on this! I'll take a look at it! :)

**Comment by Skarlso** [comment]
So... This works: 

``` ruby
    h = { 'hi' => 'there' }
    h2 = { 'hi' => false }
    assert_equal h2, JsonPath.for(h).gsub!('$.hi') { |_| false }.to_hash
```

Is that okay?

**Comment by kibs** [comment]
Looks fine to me :) great!

**Comment by Skarlso** [comment]
Coolness. :) Thanks. :)
